name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-venv git zip unzip openjdk-17-jdk \
                            build-essential autoconf automake libtool pkg-config zlib1g-dev \
                            libc6-dev libncurses5 libstdc++6 libffi-dev

        pip3 install --upgrade pip
        pip3 install cython==0.29.36 buildozer==2.0.3

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MyApp-APK
        path: bin/*.apk
