name: Build APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython kivy==2.3.1 kivymd==1.1.1 yt-dlp==2025.9.5 arabic-reshaper==3.0.0 python-bidi==0.6.6 plyer==2.1.0 Pillow==11.3.0

    - name: Initialize buildozer
      run: |
        buildozer init

    - name: Update buildozer.spec
      run: |
        sed -i 's|# title = .*|title = HefedApp|' buildozer.spec
        sed -i 's|# package.name = .*|package.name = hefed|' buildozer.spec
        sed -i 's|# package.domain = .*|package.domain = org.example|' buildozer.spec
        sed -i 's|# source.include_exts = .*|source.include_exts = py,png,jpg,kv,atlas|' buildozer.spec
        sed -i 's|# version = .*|version = 0.1|' buildozer.spec
        sed -i 's|# requirements = .*|requirements = python3,kivy==2.3.1,kivymd==1.1.1,yt-dlp==2025.9.5,arabic-reshaper==3.0.0,python-bidi==0.6.6,plyer==2.1.0,Pillow==11.3.0|' buildozer.spec
        sed -i 's|# orientation = .*|orientation = portrait|' buildozer.spec
        sed -i 's|# android.api = .*|android.api = 34|' buildozer.spec
        sed -i 's|# android.ndk = .*|android.ndk = 25b|' buildozer.spec
        sed -i 's|# android.sdk = .*|android.sdk = 34|' buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: hefed-apk
        path: bin/*.apk
