name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git build-essential zip unzip openjdk-11-jdk

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer==1.4.3
        pip install Cython==0.30.2
        pip install Kivy==2.3.1
        pip install kivymd==1.1.1
        pip install yt-dlp==2025.9.5
        pip install arabic-reshaper==3.0.0
        pip install python-bidi==0.6.6
        pip install plyer==2.1.0
        pip install Pillow==11.3.0

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: bin/*.apk
